#nätverk för proxy traefik och db nätverk
networks:
  proxy :
  db:
    


services:
  #
  traefik:
    image: traefik:v3.5 # specificera version
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro #kommunisera med socket
    networks:
      - proxy
    
  #Db redis container
  redis:
    image: redislabs/redismod
    #ports:
    #  - '6379:6379'
    networks:
     - db #existerar i egen nätverk

  web:
    build:
      context: .
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    labels: 
     - traefik.enable=true
     - traefik.docker.network=proxy # två nätverk
     - traefik.http.routers.web.rule=Host(`frontend.localhost`)
     - traefik.http.routers.web.entrypoints=web
     - traefik.http.services.web.loadbalancer.server.port=8000
    #ports:
    #  - '8000:8000'
    volumes:
      - .:/code
    depends_on:
      - redis
    networks:
    - proxy
    - db