services:
#Container web
  web: 
    build:
      context: app
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    container_name: flask-Web-application
    stop_signal: SIGINT
    environment:
      PORT: ${WEB_PORT}
    ports:
       - "${WEB_PORT}:8000"
    #healthcheck of program and http every 30 seconds
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      retries: 3
      timeout: 10s
    
    restart: unless-stopped
    volumes:
      - ./app:/app
    networks:
      - my_flask_network

networks:
  my_flask_network:
    driver: bridge # Standard är "bridge", men du kan även använda overlay, host, etc