services:
# Container opensource github web
  gitea:
    image: gitea/gitea:latest
    # Enviroment variables
    environment:
      - GITEA__database__DB_TYPE=${DB_TYPE}
      - GITEA__database__HOST=${DB_HOST}
      - GITEA__database__NAME=${DB_NAME}
      - GITEA__database__USER=${DB_USER}
      - GITEA__database__PASSWORD=${DB_PASSWD}
    restart: always
    volumes:
      - git_data:/data
    networks:
      - gitea_network
      - postgres_network
    
    ports:
      - "${WEB_PORT}:3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      retries: 3
      timeout: 10s
  #Container db
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
    - postgres_network
volumes:
  db_data:
  git_data:
networks:
  gitea_network:
  postgres_network:
  
  
    
